### ISSUE TITLE
Language dropdown options are transparent on hover

### ISSUE THREAD

**Issue by megascatterbomb** [MegaAntiCheat/MegaAntiCheat-UI#113]
This glitch doesn't affect the user's ability to select a language; it's purely a visual anomaly.

![image](https://github.com/user-attachments/assets/d613923b-adb9-4686-beb6-34fc4c50b741)

**Comment by PoorPocketsMcNewHold** [comment]
Far worse for me, on Firefox 127.0.2

https://github.com/user-attachments/assets/0f0d4122-2630-4d33-bb7c-486d9a4c5c99

Can't even select the French language, for example, at the end of the list.

**Comment by PoorPocketsMcNewHold** [comment]
[**@megascatterbomb**](https://github.com/megascatterbomb) commented on [Jul 31, 2024, 12:33 PM GMT+2](https://github.com/MegaAntiCheat/MegaAntiCheat-UI/issues/113#issuecomment-2260200459 "2024-07-31T10:33:32Z - Replied by Github Reply Comments"):
> French was only very recently added, you don't appear to be on the latest version (v0.1.0)
> 
> _Originally posted by @megascatterbomb in https://github.com/MegaAntiCheat/MegaAntiCheat-UI/issues/113#issuecomment-2260200459_

I am. On the main branch that is, latest pull and everything. 
![image](https://github.com/user-attachments/assets/33853a5d-8301-4f00-bf60-2cf503ae1930)

**Comment by SammCheese** [comment]
Issue fixed, bwomp
