### ISSUE TITLE
Profile issue when given profile image url but invalid image

### ISSUE THREAD

**Issue by cgcha** [MegaAntiCheat/MegaAntiCheat-UI#18]
Was in a game with a user where the avatar listed as "Not Found" and instead showed `Profile` where the image should be. Didn't get a screenshot of it, but I assume the default avatar was supposed to fill in. 

https://avatars.steamstatic.com/663af8d61621f09c04e23aa279c39ee4f4193bdc_full.jpg

This was their avatar, which when put into a browser says "Not Found".

**Comment by SammCheese** [comment]
Taking a look immediately, thank you for bringing this to my attention

**Comment by SammCheese** [comment]
Fixed in [9cffb60](https://github.com/MegaAntiCheat/MegaAntiCheat-UI/commit/9cffb60bf9d7aa8c07fc5c3d08f7f5a692d4982a)
