### ISSUE TITLE
Ability to call a votekick on a player

### ISSUE THREAD

**Issue by Bash-09** [MegaAntiCheat/MegaAntiCheat-UI#25]
Not the most important feature, but it would be nice to be able to call a votekick on a player from within the UI. The backend will still have to implement an API endpoint to support this (https://github.com/MegaAntiCheat/client-backend/issues/55).

**Comment by SammCheese** [comment]
Already Planned here ;) 

https://github.com/MegaAntiCheat/MegaAntiCheat-UI/blob/main/src/components/TF2/Player/Player.tsx#L104-L111

**Comment by Bash-09** [comment]
I've implemented an endpoint on the backend that you can use :)
https://github.com/MegaAntiCheat/client-backend/issues/55
https://github.com/MegaAntiCheat/client-backend/wiki/API-Specification#commands-post

**Comment by SammCheese** [comment]
Added ;)
