### ISSUE TITLE
Mega Anti Cheat Icon

### ISSUE THREAD

**Issue by B0xF0xplays** [MegaAntiCheat/MegaAntiCheat-UI#3]
I have an Icon ( suggestion ) for M.A.C. That I made in 1 minutes
![Mega Anti Cheat](https://github.com/MegaAntiCheat/MegaAntiCheat-UI/assets/139339830/0ab24723-cd0b-4ac6-b9af-588a2769cb99)

Hope it is / will inspire the final Icon of Mega Anti Cheat

**Comment by lili7h** [comment]
colour scheme reminds me of german empire..

**Comment by megascatterbomb** [comment]
User was banned for this post.
