### ISSUE TITLE
[Discussion] Linux Support

### ISSUE THREAD

**Issue by Jazztache** [MegaAntiCheat/MegaAntiCheat-UI#33]
Hello!

I was just wondering if there were any plans to bring the UI to Linux when it comes out.
Seeing as Valve is heavily supporting Linux with the Steam Deck right now, and the tech stack for this project mostly seems to be webtech (React/TypeScript). I recon maintaining a Linux version would be both a good idea and relatively easy.

There are likely decent few people that play TF2 on Linux that would be interested in using/contributing to the project.

Thankyou!

**Comment by lili7h** [comment]
The UI and client already support, and always will support, Linux. Most of the devs build and run on Linux. The UI operates in a browser (which is OS independent) and the backend core is compiled to all targets. Specific distribution support may need some extra consideration once we start to exit beta and have a wider captive audience and more capability to dig into the nitty gritty OS specifics.

**Comment by lili7h** [comment]
I am curious as to why a React/TS techstack _wouldn't_ be linux native? What/how did  you mean by this? :)

**Comment by Bash-09** [comment]
Hiya! Yes as Lilith said. I run Linux on my gaming machine so as long as I'm working on it, it will definitely support Linux. Currently the UI is hosted as a web app so you can connect to it anywhere with a browser, even remotely if you really wanted to set that up, and we are trying to keep the native app as platform independent as possible. 

We also document the API used for the web UI, so anybody is free to develop their own frontend for the app to use with it.
