### ISSUE TITLE
Dropdowns obscured by UI in Recently Played With tab

### ISSUE THREAD

**Issue by Mistyttm** [MegaAntiCheat/MegaAntiCheat-UI#35]
**OS**: Arch Linux

**Browser**: Firefox 121.0

**Build**: Latest alpha as of 06/01/24 built with `client_backend`

**Description**: In the `Recently Played With` tab there is a drop down to retroactively assign players. This drop down when opened displays underneath the rest of the UI and creates a scroll-box within the div. From my perspective this seems very unintuitive so I assumed it might be a bug

![image](https://github.com/MegaAntiCheat/MegaAntiCheat-UI/assets/51770769/7cc889eb-2ab0-4123-ba95-fa21c96cc5bc)

**Comment by SammCheese** [comment]
Yeah, I have yet to find out how to fix it :D

**Comment by megascatterbomb** [comment]
We're looking into redoing this page with additional/different functionality; once we've decided what to do this issue should get fixed in the process.
