### ISSUE TITLE
condensed menu doesn't count bots as cheaters

### ISSUE THREAD

**Issue by jkibort928** [MegaAntiCheat/MegaAntiCheat-UI#36]
The menu shows 0 cheaters, when I have multiple players in the lobby marked as bots. It would be helpful for it to add cheaters and bots together as the same thing

![image](https://github.com/MegaAntiCheat/MegaAntiCheat-UI/assets/144510012/091b96af-a1d3-432f-ae72-e2aa03e7ea65)

**Comment by SammCheese** [comment]
fixed in 60e7995
