### ISSUE TITLE
This wont work.

### ISSUE THREAD

**Issue by qtTF2** [MegaAntiCheat/MegaAntiCheat-UI#4]
This project just simply does not work. My concerns that are this is useless and completely waste of development time and everyones time.
* As cheaters/bots (or them dont give a shit about it) can get a new accounts or create a set of alternative accounts;
* There is no automation regarding the AntiCheat its all manual when it comes to detection.
* I doubt AI will work since there is a feature which hides Aimbot from demo recordings (and source demo recordings are not reliable!)

**Comment by SammCheese** [comment]
Brilliant, Mind elaborating? :trollface:

**Comment by SammCheese** [comment]
This is the UI. If you have concerns of functionality, please redirect feedback to the Discord server or the more relevant Repositories.

**Comment by qtTF2** [comment]
> This is the UI. If you have concerns of functionality, please redirect feedback to the Discord server or the more relevant Repositories.

Im unable to complain about the bloat due to megascatterbomb strict censorship.

**Comment by SammCheese** [comment]
> since a real AntiCheat should not have any bloat (GUI) in it and it should be rewritten along with the game written in.
You can run the clientbackend without the UI, that's not an issue.
