### ISSUE TITLE
Pressing save does nothing in first time configuration

### ISSUE THREAD

**Issue by W-i-n-7** [MegaAntiCheat/MegaAntiCheat-UI#40]
nothing to add to the title

**Comment by megascatterbomb** [comment]
Confirmed bug exists on main branch:
- When I manually typed in the word "test" into either steam api key or rcon password, the save button worked and the string "tes" was written to the config.
- When I tried to paste in something without typing anything, the save button does nothing.

This commit appears to be responsible for the bug: https://github.com/MegaAntiCheat/MegaAntiCheat-UI/commit/2c537eae873a22d3a7f259d6859429ffd6576fed
