### ISSUE TITLE
New Icon idea (Read pls!)

### ISSUE THREAD

**Issue by B0xF0xplays** [MegaAntiCheat/MegaAntiCheat-UI#5]
Hey It's me B0xF0xplays Again Sorry that I posted a suspicious but I hope this one is better!
![Mega Anti Cheat V 4 (Not Special Greman flag which I am sorry about ;( )](https://github.com/MegaAntiCheat/MegaAntiCheat-UI/assets/139421606/8027fc10-3619-4bf8-a702-ec4084f58ca2)
I hope this one is / will inspire the M.A.C. Logo

Sincerely: B0xF0xplays

**Comment by SammCheese** [comment]
This is not up to me. The Icon is something you should suggest to the higher-ups xd.

**Comment by SammCheese** [comment]
I will close this for now
