### ISSUE TITLE
Vite instead of Webpack?

### ISSUE THREAD

**Issue by 2l42h3r** [MegaAntiCheat/MegaAntiCheat-UI#51]
Hi,
this is not an issue, however discussions are not enabled for this project, so I will post here.
The React ecosystem (and multiple other web frameworks) seem to be moving towards using Vite as a build tool instead of Webpack (Vite is used by default by SolidJS, Svelte, Vue, and now Angular; the React framework Remix is also switching currently) and even the official React docs no longer recommend the default create-react-app toolstack (with Webpack). Moving to Vite would also mean faster builds and potentially less configuration boilerplate.
Is there a reason for this project to use Webpack?
If there is no opposition from maintainers, I would be interested in creating a PR migrating the project to Vite.

**Comment by SammCheese** [comment]
Intriguing, I'd be down for it

**Comment by meatmeatmeatmeatmeatmeat** [comment]
I went ahead and gave it a go, hope that is alright :) 
[Pull request is here](https://github.com/MegaAntiCheat/MegaAntiCheat-UI/pull/52)
