### ISSUE TITLE
Why react?

### ISSUE THREAD

**Issue by Pagwin-Fedora** [MegaAntiCheat/MegaAntiCheat-UI#7]
I just see that the repo description and README say React and I'm wondering if there are any reasons for choosing it beyond it being one of the most popular ways to do UI atm (source for this metric being my gut).

**Comment by lili7h** [comment]
The current build of the front end ui lives in a separate branch to master. Essentially, we wanted something that ran in the steam overlay browser, which meant JavaScript/TypeScript. After that, i think its just up to whatever the front end dev is most comfortable with

**Comment by SammCheese** [comment]
React my belove

**Comment by Pagwin-Fedora** [comment]
ah okay makes sense, I'm mildly curious on if the steam overlay browser supports wasm allowing for a rust web framework but that's pedantics so I'll close this.
