### ISSUE TITLE
PC TURNED INTO KIWIS

### ISSUE THREAD

**Issue by rosne-gamingyt** [MegaAntiCheat/MegaAntiCheat-UI#9]
PLS HELP QHEN I RAN THIS IN ROBLOX BY ACCIDENT MY PC RAN MEMZ AND 144214 OTHER RATS!! ITS NOW KIWIS MY 37373737377-TI NVDIA GPU IS RUINED!😭😭😭😭😭

**Comment by SammCheese** [comment]
Intriguing. Please tell me more. (I don't really care, I just have a thing for kiwis)

**Comment by rosne-gamingyt** [comment]
> Intriguing. Please tell me more. (I don't really care, I just have a thing for kiwis)

Oh yeah my LEFT NUT GOT DDOSED BY REALTIY/TROLLSEC!

**Comment by SammCheese** [comment]
Not about kiwis. I'm severely disappointed. Closing immediately and ordering an airstrike.
